apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-08-22T15:25:48Z"
  generation: 1
  labels:
    app: jenkins
  name: jenkins
  namespace: default
  resourceVersion: "13368"
  uid: ee09098f-3ab7-4d0b-845a-9d0cff3b20d8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins
        imagePullPolicy: Always
        name: jenkins
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-22T15:26:01Z"
    lastUpdateTime: "2022-08-22T15:26:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-22T15:25:48Z"
    lastUpdateTime: "2022-08-22T15:26:01Z"
    message: ReplicaSet "jenkins-6845b6db47" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-08-22T15:33:47Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  generateName: jenkins-
  labels:
    app: jenkins
  name: jenkins-774gx
  namespace: default
  resourceVersion: "17156"
  uid: f38a92fc-1383-4003-9693-46e79b767396
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.4.176
  clusterIPs:
  - 10.96.4.176
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32233
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.172.243.115
