cidr_range = "10.0.0.0/16"
vpc_network_name = "vpc"
subnetwork_name = "subnetwork"
instance_name = "test-instance"
zone = "us-central1-a"
region = "us-central1"
instance_type = "f1-micro"
image = "debian-10-buster-v20220719"
